In [1]:
#Q1
import numpy as np
arr1 = np.arange(10, 51, 5)
print("Array is ", arr1)
print("Shape is ", arr1.shape)
print("Size is ", arr1.size)
print("Data type is ", arr1.dtype)

Array is  [10 15 20 25 30 35 40 45 50]
Shape is  (9,)
Size is  9
Data type is  int64


In [2]:
#Q2
arr2 = np.random.randint(1, 101, size=(4, 5))
print("\nRandom 4x5 matrix:\n", arr2)
print("Max value:", arr2.max(), "at index", np.unravel_index(arr2.argmax(), arr2.shape))
print("Min value:", arr2.min(), "at index", np.unravel_index(arr2.argmin(), arr2.shape))


Random 4x5 matrix:
 [[40 31 67 73 26]
 [ 4 84 38 33 15]
 [ 6 11 54  6  2]
 [77 73 99  5 49]]
Max value: 99 at index (np.int64(3), np.int64(2))
Min value: 2 at index (np.int64(2), np.int64(4))


In [3]:
#Q3
arr3 = np.arange(1, 25)
mat3 = arr3.reshape(4, 6)
print("Reshaped 4x6 matrix is \n", mat3)
print("2nd row is ", mat3[1])
print("3rd column is ", mat3[:, 2])

Reshaped 4x6 matrix is 
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
2nd row is  [ 7  8  9 10 11 12]
3rd column is  [ 3  9 15 21]


In [4]:
#Q4
arr4 = np.random.randint(0, 51, size=15)
print("Original array is ", arr4)
arr4[arr4 > 25] = -1
print("Modified array is ", arr4)

Original array is  [ 1 10 18  6 47  0  4 28 26 43  6 23 45  5 42]
Modified array is  [ 1 10 18  6 -1  0  4 -1 -1 -1  6 23 -1  5 -1]


In [5]:
#Q5
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])
print("Addition is ", a + b)
print("Subtraction is ", a - b)
print("Multiplication is ", a * b)
print("Division is ", a / b)

Addition is  [11 22 33 44 55]
Subtraction is  [ -9 -18 -27 -36 -45]
Multiplication is  [ 10  40  90 160 250]
Division is  [0.1 0.1 0.1 0.1 0.1]


In [6]:
#Q6
arr6 = np.random.rand(5, 5)
print("5x5 Random Float Matrix is \n", arr6)
print("Mean is ", np.mean(arr6))
print("Median is ", np.median(arr6))
print("Variance is ", np.var(arr6))
print("Standard Deviation is ", np.std(arr6))

5x5 Random Float Matrix is 
 [[0.98933714 0.81821006 0.71798061 0.39300042 0.68184936]
 [0.02758598 0.76095179 0.70260786 0.6194186  0.91848741]
 [0.01203801 0.08753652 0.77312923 0.65088272 0.63066855]
 [0.85760648 0.97411897 0.66815058 0.31639508 0.46628409]
 [0.16829096 0.68441707 0.06671014 0.09130513 0.63600757]]
Mean is  0.5485188125661294
Median is  0.650882717654214
Variance is  0.09405518151605191
Standard Deviation is  0.3066841722620388


In [7]:
#Q7
A = np.arange(1, 7).reshape(3, 2)
B = np.arange(7, 13).reshape(2, 3)
result = A @ B
print("Matrix A is \n", A)
print("Matrix B is \n", B)
print("Matrix multiplication result is \n", result)

Matrix A is 
 [[1 2]
 [3 4]
 [5 6]]
Matrix B is 
 [[ 7  8  9]
 [10 11 12]]
Matrix multiplication result is 
 [[ 27  30  33]
 [ 61  68  75]
 [ 95 106 117]]


In [8]:
#Q8
arr8 = np.arange(1, 37).reshape(6, 6)
print("Original 6x6 matrix is \n", arr8)
arr8[1:4, 1:4] = 0
print("Modified Matrix is \n", arr8)

Original 6x6 matrix is 
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
Modified Matrix is 
 [[ 1  2  3  4  5  6]
 [ 7  0  0  0 11 12]
 [13  0  0  0 17 18]
 [19  0  0  0 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]


In [9]:
#Q9
arr9 = np.array([5, 10, 15, 20, 25])
modified9 = np.where(arr9 > 15, 99, 0)
print("Original array is ", arr9)
print("Modified array is ", modified9)

Original array is  [ 5 10 15 20 25]
Modified array is  [ 0  0  0 99 99]


In [10]:
#Q10
arr10 = np.full((4, 4), 10)
sub = np.array([0, 1, 2, 3])
result10 = arr10 - sub
print("Original 4x4 array is \n", arr10)
print("Result after broadcasting is \n", result10)

Original 4x4 array is 
 [[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]
Result after broadcasting is 
 [[10  9  8  7]
 [10  9  8  7]
 [10  9  8  7]
 [10  9  8  7]]
