In [11]:
#Q1
import numpy as np

arr = np.arange(10, 51, 5)
print("Array:", arr)
print("Shape:", arr.shape)
print("Size:", arr.size)
print("Dtype:", arr.dtype)

Array: [10 15 20 25 30 35 40 45 50]
Shape: (9,)
Size: 9
Dtype: int64


In [12]:
#Q2
import numpy as np

rng = np.random.default_rng(seed=42)
mat = rng.integers(low=1, high=101, size=(4, 5))
print("Matrix:\n", mat)

max_val = mat.max()
min_val = mat.min()
max_idx = np.unravel_index(mat.argmax(), mat.shape)
min_idx = np.unravel_index(mat.argmin(), mat.shape)

print("Max value:", max_val, "at index:", max_idx)
print("Min value:", min_val, "at index:", min_idx)

Matrix:
 [[ 9 78 66 44 44]
 [86  9 70 21 10]
 [53 98 74 77 72]
 [79 52 13 84 46]]
Max value: 98 at index: (np.int64(2), np.int64(1))
Min value: 9 at index: (np.int64(0), np.int64(0))


In [13]:
#Q3
import numpy as np

arr = np.arange(1, 25)
mat = arr.reshape(4, 6)
second_row = mat[1, :]
third_col = mat[:, 2]

print("Matrix:\n", mat)
print("2nd row:", second_row)
print("3rd column:", third_col)

Matrix:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
2nd row: [ 7  8  9 10 11 12]
3rd column: [ 3  9 15 21]


In [14]:
#Q4
import numpy as np

rng = np.random.default_rng(seed=0)
arr = rng.integers(0, 51, size=15)
print("Original:", arr)
mask = arr > 25
arr[mask] = -1
print("Modified:", arr)

Original: [43 32 26 13 15  2  3  0  8 41 33 46 25 30 49]
Modified: [-1 -1 -1 13 15  2  3  0  8 -1 -1 -1 25 -1 -1]


In [15]:
#Q5
import numpy as np

a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

Addition: [11 22 33 44 55]
Subtraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [16]:
#Q6
import numpy as np

rng = np.random.default_rng(seed=123)
mat = rng.random((5, 5))
print("Matrix:\n", mat)

mean = mat.mean()
median = np.median(mat)
variance = mat.var()
std_dev = mat.std()

print("Mean:", mean)
print("Median:", median)
print("Variance:", variance)
print("Std Dev:", std_dev)

Matrix:
 [[0.68235186 0.05382102 0.22035987 0.18437181 0.1759059 ]
 [0.81209451 0.923345   0.2765744  0.81975456 0.88989269]
 [0.51297046 0.2449646  0.8242416  0.21376296 0.74146705]
 [0.6299402  0.92740726 0.23190819 0.79912513 0.51816504]
 [0.23155562 0.16590399 0.49778897 0.58272464 0.18433799]]
Mean: 0.49378941294359263
Median: 0.5129704552295319
Variance: 0.08228072862984435
Std Dev: 0.28684617590242395


In [17]:
#Q7
import numpy as np

A = np.arange(1, 7).reshape(3, 2)
B = np.arange(7, 13).reshape(2, 3)
C = A @ B
print("A:\n", A)
print("B:\n", B)
print("A @ B:\n", C)

A:
 [[1 2]
 [3 4]
 [5 6]]
B:
 [[ 7  8  9]
 [10 11 12]]
A @ B:
 [[ 27  30  33]
 [ 61  68  75]
 [ 95 106 117]]


In [18]:
#Q8
import numpy as np
mat = np.arange(1, 37).reshape(6, 6)
print("Original:\n", mat)
center = mat[2:5, 2:5]
center[:, :] = 0
print("Modified:\n", mat)

Original:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
Modified:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14  0  0  0 18]
 [19 20  0  0  0 24]
 [25 26  0  0  0 30]
 [31 32 33 34 35 36]]


In [19]:
#Q9
import numpy as np
arr = np.array([5, 10, 15, 20, 25])
result = np.where(arr > 15, 99, 0)
print("Original:", arr)
print("Result:", result)

Original: [ 5 10 15 20 25]
Result: [ 0  0  0 99 99]


In [20]:
#Q10
import numpy as np

mat = np.full((4, 4), 10)
row = np.array([0, 1, 2, 3])

result = mat - row
print("Original matrix:\n", mat)
print("Row to subtract:", row)
print("Result:\n", result)

Original matrix:
 [[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]
Row to subtract: [0 1 2 3]
Result:
 [[10  9  8  7]
 [10  9  8  7]
 [10  9  8  7]
 [10  9  8  7]]
